SET DATESTYLE = "ISO, DMY";

CREATE TABLE FAMILY_MEMBERS (
	ID SERIAL PRIMARY KEY,
	NAME TEXT UNIQUE,
	DATE_OF_BIRTH DATE
);

CREATE TABLE PRODUCTS (
	ID SERIAL PRIMARY KEY,
	NAME TEXT UNIQUE,
	CATEGORY TEXT,
	PRICE_PER_ITEM INT
);

CREATE TABLE FAMILY_MEMBERS_JOB (
	ID SERIAL PRIMARY KEY,
	MEMBER_ID INT REFERENCES FAMILY_MEMBERS (ID),
	OCCUPATION TEXT,
	ORGANIZATION TEXT,
	SALARY BIGINT,
	STARTING_DATE DATE
);

CREATE TABLE EXPENCES (
	ID SERIAL PRIMARY KEY,
	DATE_OF_PURCHASE DATE,
	MEMBER_ID INT REFERENCES FAMILY_MEMBERS (ID),
	PRODUCT_ID INT REFERENCES PRODUCTS (ID),
	QUANTITY INT
);

